# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# General
site_name: Data Structures and Algortithms Documentation
site_url: https://sm2774us.github.io/Data_Structures_And_Algorithms
site_author: Shaikat Majumdar
dev_addr: '127.0.0.1:8080'

# Repository
repo_name: 'sm2774us/Data_Structures_And_Algorithms'
repo_url: 'https://github.com/sm2774us/Data_Structures_And_Algorithms'
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024 Shaikat Majumdar

extra_javascript:
  - javascript/config.js
  - https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

# Configuration
theme:
  name: material
  custom_dir: src/overrides
  logo: favicon.ico
  favicon: favicon.ico
  icon:
    repo: fontawesome/brands/github
    edit: material/file-document-edit-outline
  palette:
    scheme: slate
  palette:
    - scheme: cpalgo
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode    
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.indexes
    - navigation.path
    - navigation.top    
    - search.highlight
    - search.suggest
    - toc.integrate

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
      tex_inline_wrap: ['$', '$']
      tex_block_wrap: ['$$', '$$']
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: 'sm2774us'
      repo: 'Data_Structures_And_Algorithms'
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - meta
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - tags:
      tags_file: tags.md
  - literate-nav:
      nav_file: navigation.md  
  - git-revision-date-localized:
      enable_creation_date: true
      enabled: !ENV [MKDOCS_ENABLE_GIT_REVISION_DATE, False]
  - git-authors
  - git-committers:
      repository: sm2774us/Data_Structures_And_Algorithms
      docs_path: docs/
      token: !ENV MKDOCS_GIT_COMMITTERS_APIKEY
      enabled: !ENV [MKDOCS_ENABLE_GIT_COMMITTERS, False]
  - mkdocstrings:
      handlers:
        python:
          options:
            separate_signature: true
            show_signature_annotations: true
            parameter_headings: false
            signature_crossrefs: true
            show_source: false
            summary: true
            show_root_heading: true
            show_root_full_path: false
            show_bases: false
  - macros
  - rss

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascript/init_kapa_widget.js

extra:
  analytics:
    provider: google
    property: G-2X4JR4S4FB

# nav:
#   - Home: 'index.md'
#   - Data Structures:
#       - Overview: 'data_structures/DATA_STRUCTURES.md'
#   - Algortithms:
#       - Overview: 'algorithms/ALGORITHMS.md'
#   - Miscellaneous:
#       - Overview: 'miscellaneous/MISCELLANEOUS.md'
