# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# General
site_name: Data Structures and Algortithms Documentation
site_url: https://sm2774us.github.io/Data_Structures_And_Algorithms
site_author: Shaikat Majumdar
dev_addr: '127.0.0.1:8080'

# Repository
repo_name: 'sm2774us/Data_Structures_And_Algorithms'
repo_url: 'https://github.com/sm2774us/Data_Structures_And_Algorithms'
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024 Shaikat Majumdar

# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  logo: favicon.ico
  favicon: favicon.ico
  icon:
    repo: fontawesome/brands/github
    edit: material/file-document-edit-outline
  palette:
    scheme: slate
  palette:
    - scheme: cpalgo
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode    
  features:
    - navigation.tabs
    - search.suggest
    - toc.integrate
    - content.code.copy

extra_javascript:
  - javascript/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - meta
  - toc:
      permalink: true

plugins:
  - mkdocs-simple-hooks:
      hooks:
          on_env: "hooks:on_env"
  - search
  - tags:
      tags_file: tags.md
  - literate-nav:
      nav_file: navigation.md  
  - git-revision-date-localized:
      enable_creation_date: true
      enabled: !ENV [MKDOCS_ENABLE_GIT_REVISION_DATE, False]
  - git-authors
  - git-committers:
      repository: sm2774us/Data_Structures_And_Algorithms
      docs_path: docs/
      token: !ENV MKDOCS_GIT_COMMITTERS_APIKEY
      enabled: !ENV [MKDOCS_ENABLE_GIT_COMMITTERS, False]
  - mkdocstrings:
      handlers:
        python:
          options:
            separate_signature: true
            show_signature_annotations: true
            parameter_headings: false
            signature_crossrefs: true
            show_source: false
            summary: true
            show_root_heading: true
            show_root_full_path: false
            show_bases: false
  - macros
  - rss

extra:
  analytics:
    provider: google
    property: G-2X4JR4S4FB

# nav:
#   - Home: 'index.md'
#   - Data Structures:
#       - Overview: 'data_structures/DATA_STRUCTURES.md'
#   - Algortithms:
#       - Overview: 'algorithms/ALGORITHMS.md'
#   - Miscellaneous:
#       - Overview: 'miscellaneous/MISCELLANEOUS.md'
