name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4    

      - name: Configure Git Credentials
        run: |
          git config user.name "Shaikat Majumdar"
          git config user.email sm2774us@gmail.com

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: set cache id
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: use cache      
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: install dependencies
        run: python -m pip install ".[docs]"

      - name: build & deploy
        run: mkdocs gh-deploy --force
